### ISSUE TITLE
Can't make request to api when passing variable as argument from file to create it

### ISSUE THREAD

**Issue by SebaRossi94** [Ponytech/appstoreconnectapi#19]
Hello i've been testing the library for the first time, i was able to do some requests to fetch app info using it but i had some issues when trying to pass the key_id and issuer_id parameters from a file.

If i do this:

`ios_api = Api(key_id = "XXXXXXXX", key_file = APPSTORECONNECT_KEY_PATH, issuer_id = "XXXXXXXXXXXXXX")`

The library works fine, but if i do this:

```
f = open(KEY_ID_FILE_PATH, "r")
KEY_ID = f.readline()


f_1 = open(ISSUER_ID_FILE_PATH, "r")
ISSUER_ID = f_1.readline()


ios_api = Api(key_id = KEY_ID, key_file = APPSTORECONNECT_KEY_PATH, issuer_id = ISSUER_ID)
f.close()
f_1.close()
apps = ios_api.list_apps(sort = "name")
for app in apps:
    print(app.name, app.sku)
```

The output is the following:

```
Traceback (most recent call last):
  File "appstoreconnect-test.py", line 24, in <module>
    for app in apps:
  File "C:\Users\Seba\.virtualenvs\google-console-api-CfTql0CN\lib\site-packages\appstoreconnect\api.py", line 157, in __next__
    self.fetch_page()
  File "C:\Users\Seba\.virtualenvs\google-console-api-CfTql0CN\lib\site-packages\appstoreconnect\api.py", line 174, in fetch_page
    self.payload = self.api._api_call(self.url)
  File "C:\Users\Seba\.virtualenvs\google-console-api-CfTql0CN\lib\site-packages\appstoreconnect\api.py", line 222, in _api_call
    raise APIError(payload.get('errors', [])[0].get('detail', 'Unknown error'))
appstoreconnect.api.APIError: Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

Even though i double checked that the strings KEY_ID and ISSUER_ID are exactly the same that i put manually.
Any help is welcomed, thanks in advance

**Comment by SebaRossi94** [comment]
Seems that i had an issue with the files themselves. I had an extra line in each of them that when reading it was creating the wrong strings. Now this work as expected
