### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by lastseenjustnow** [Ponytech/appstoreconnectapi#42]
I guess there's a problem that Api class requesting the data from the AppStore, but in the end it doesn't close the connection opened. So I'm facing the issue:
```
Exception ignored in: <function Api.__del__ at 0x7fb0e9e5ba70>
Traceback (most recent call last):
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/appstoreconnect/api.py", line 70, in __del__
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/appstoreconnect/api.py", line 327, in _submit_stats
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/api.py", line 117, in post
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/sessions.py", line 520, in request
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/sessions.py", line 701, in merge_environment_settings
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/utils.py", line 805, in get_environ_proxies
  File "/Users/vladislav/PycharmProjects/sidr_gcp_functions/venv/lib/python3.7/site-packages/requests/utils.py", line 789, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2645, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2622, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2569, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down
```

Import gc; gc.collect()  didn't really help.

Has anyone faced this issue?

**Comment by lastseenjustnow** [comment]
Apparently, an error is pretty much generic.

**Comment by tomatobin** [comment]
when init Api，use submit_stats=False should fix this error
