### ISSUE TITLE
Basic question on usage

### ISSUE THREAD

**Issue by XoliloX** [Ponytech/appstoreconnectapi#47]
Dear,

Sorry to bother with such a question (I'm a lost R user here) but after after compiling the authentification, I get 

```
Exception ignored in: <function Api.__del__ at 0x7faef65d6670>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appstoreconnect/api.py", line 72, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appstoreconnect/api.py", line 333, in _submit_stats
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 117, in post
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 61, in request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connection.py", line 380, in connect
ModuleNotFoundError: import of time halted; None in sys.modules

Process finished with exit code 0

```
Also, trying to get reporting into PyCharm, I need the `Vendorid` which is not an obvious parameter to me (where is it?).

Thanks in advance for your help !

Best,
D.

**Comment by XoliloX** [comment]
Limitations are related to Appstoreconnect, not to this package.

**Comment by ppawlak** [comment]
Hi,

Sorry for not replying before, and thanks for marking the issue as closed if it's related to this package 😄

**Comment by XoliloX** [comment]
Hi,

No worries, thanks a lot !!!

Best,
D.
